// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChE23oQe0lYW_Y2TAKbCCjl1ox5yTikTc',
    appId: '1:203503274066:web:d1b68e01a632af4186378b',
    messagingSenderId: '203503274066',
    projectId: 'tru-dawson-project-2023',
    authDomain: 'tru-dawson-project-2023.firebaseapp.com',
    storageBucket: 'tru-dawson-project-2023.appspot.com',
    measurementId: 'G-K211QH0BTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUIZyBwKtZRKaSR4T3801SOFlyZ24r9Es',
    appId: '1:203503274066:android:79a3c897352c751286378b',
    messagingSenderId: '203503274066',
    projectId: 'tru-dawson-project-2023',
    storageBucket: 'tru-dawson-project-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2g9BNceSju5kU19kJjtC6VczEs129sLQ',
    appId: '1:203503274066:ios:d90f78b5420cdb0986378b',
    messagingSenderId: '203503274066',
    projectId: 'tru-dawson-project-2023',
    storageBucket: 'tru-dawson-project-2023.appspot.com',
    iosBundleId: 'com.example.truDawsonProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2g9BNceSju5kU19kJjtC6VczEs129sLQ',
    appId: '1:203503274066:ios:1a2836a3b7123d5e86378b',
    messagingSenderId: '203503274066',
    projectId: 'tru-dawson-project-2023',
    storageBucket: 'tru-dawson-project-2023.appspot.com',
    iosBundleId: 'com.example.truDawsonProject.RunnerTests',
  );
}
